name: Bug Report
description: File a bug report
title: "[Bug]: "
labels: ["bug", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: usage
    attributes:
      label: EPPlus usage
      description: If you have a commercial license, please log in to our [support portal](https://epplussoftware.com) and create an empty ticket with a reference to this issue.
      options:
        - label: I use EPPlus in a commercial company
        - label: I use EPPlus in a noncommercial organization
        - label: I use EPPlus for personal use
  - type: input
    id: environment
    attributes:
      label: Environment
      description: What kind of environment do you run EPPlus in?
      placeholder: ex. Windows
    validations:
      required: true
  - type: input
    id: eppVersion
    attributes:
      label: Epplus version
      description: What version of EPPlus are you using?
      placeholder: ex. 6.2.7
    validations:
      required: true
  - type: input
    id: spreadsheetApp
    attributes:
      label: Spreadsheet application
      description: What kind of spreadsheet application (if any) are you using?
      placeholder: ex. Excel
    validations:
      required: false
  - type: textarea
    id: issueDescription
    attributes:
      label: Description
      description: You must provide enough information for us to be able to understand and replicate the issue. The better and more detailed the issue is described the more likely it is that we can fix it. Unit tests or a combination of a sample workbook and code that replicates the issue seems to be a winning concept.
      placeholder: detailed description of the bug/issue
      value: "A bug happened!"
    validations:
      required: true
  
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
